dubbo:
  application:
    name: gds-service
  registry:
    address: zookeeper://192.168.159.129:2181
  protocol:
    port: -1
spring:
  datasource:
    url: jdbc:mysql:///db_goods?serverTimezone=GMT%2B8
    username: root
    password: 123
    driver-class-name: com.mysql.cj.jdbc.Driver
